const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {Store}=require('./store'),{uploadOne}=require('./uploader');
function fixture(){let t=Date.now();const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cargadero-'));let store=new Store(dir,'2',{now:()=>t});return {dir,get store(){return store},time:ms=>t+=ms,reopen:()=>{store.close();store=new Store(dir,'2',{now:()=>t});},close:()=>{store.close();fs.rmSync(dir,{recursive:true,force:true})}};}
const event={majorEventType:5,subEventType:1,employeeNoString:'DRIVER-2',cardNo:'0310250706'};
const roster={ok:true,complete:true,version:2,station_id:'2',count:1,generated_at:new Date().toISOString(),items:[{employeeNo:'DRIVER-2',name:'VICTOR',kind:'driver',active:true,company_code:'3',pin_user_id:2,cards:['0310250706']}]};
test('SQLite persists roster, UUID, leading zero and closed loads across restarts',()=>{const f=fixture();f.store.inventory(roster);f.reopen();const a=f.store.access(event).load;assert.equal(a.card_no,'0310250706');f.store.meter(true);f.time(1000);f.store.meter(true);f.time(1000);const closed=f.store.meter(false).load;assert.equal(closed.liters,0);assert(closed.pump_started_at);assert.equal(Date.parse(closed.ended_at)-Date.parse(closed.pump_started_at),2000);assert.equal(f.store.snapshot(a.local_id).body.liters,undefined);assert.equal(f.store.snapshot(a.local_id).body.flow_l_min,undefined);assert(closed.ended_at);f.reopen();assert.equal(f.store.read(a.local_id).liters,0);assert.equal(f.store.get('roster').items[0].cards[0],'0310250706');f.close();});
test('Lost server acknowledgement: retry uses same UUID/revision, no deletion',async()=>{const f=fixture();const a=f.store.meter(true).load;f.time(1000);f.store.meter(false);const got=[];let responseLost=true;const server=async(url,opt)=>{const b=JSON.parse(opt.body.get('record'));got.push(b);if(responseLost){responseLost=false;throw Error('lost reply');}return {ok:true,json:async()=>({ok:true,id:123,local_id:b.local_id,revision:b.revision})}};await assert.rejects(uploadOne(f.store,a.local_id,'http://example',server));f.reopen();await uploadOne(f.store,a.local_id,'http://example',server);assert.equal(got[0].local_id,got[1].local_id);assert.equal(got[0].revision,got[1].revision);assert.equal(f.store.status().pending,0);assert(f.store.read(a.local_id));f.close();});
test('New liters arriving during upload remain pending',async()=>{const f=fixture();const a=f.store.meter(true).load;await uploadOne(f.store,a.local_id,'http://example',async(u,o)=>{const b=JSON.parse(o.body.get('record'));f.time(1000);f.store.meter(true);return {ok:true,json:async()=>({ok:true,id:1,local_id:b.local_id,revision:b.revision})}});assert.equal(f.store.status().pending,1);f.close();});
test('Photo survives restart and acknowledgement prevents repeated bytes',async()=>{const f=fixture();const a=f.store.meter(true).load;f.time(1000);f.store.meter(false);const image=Buffer.alloc(1200,4);image.set([255,216,255]);const sha=f.store.photo(a.local_id,image);f.reopen();assert(fs.existsSync(f.store.snapshot(a.local_id).photos[0].file));let calls=0;const server=async(u,o)=>{const b=JSON.parse(o.body.get('record'));assert.equal(o.body.has('photo_'+sha),calls++===0);return {ok:true,json:async()=>({ok:true,id:1,local_id:b.local_id,revision:b.revision})}};await uploadOne(f.store,a.local_id,'http://example',server);f.store.photoFailure(a.local_id);await uploadOne(f.store,a.local_id,'http://example',server);f.close();});
test('No internet never clears roster; stale identities are recorded for review',()=>{const f=fixture();f.store.inventory(roster);assert.throws(()=>f.store.inventory({ok:true,items:[]}));f.time(73*3600000);const a=f.store.access(event).load;assert.equal(a.employee_no,'DRIVER-2');assert(a.review_reasons.includes('padron_ausente_o_vencido'));f.close();});
test('PLC loss and process restart do not invent liters',()=>{const f=fixture();const a=f.store.meter(true).load;f.time(1000);f.store.meter(true);f.time(60000);f.store.meter(true);assert.equal(f.store.read(a.local_id).liters,0);f.reopen();f.time(60000);f.store.meter(false);const b=f.store.read(a.local_id);assert.equal(b.liters,0);assert(b.ended_at);assert(b.review_reasons.includes('reinicio_durante_carga'));assert(b.review_reasons.includes('intervalo_sin_medicion'));f.close();});
test('Manual and RFID race uses one local load; duplicate accepted event ignored',()=>{const f=fixture();f.store.inventory(roster);const manual=f.store.meter(true).load;const attributed=f.store.access(event);assert.equal(attributed.load.local_id,manual.local_id);assert.equal(attributed.load.access_method,'rfid');assert.equal(f.store.access(event),null);assert.equal(f.store.status().total,1);f.close();});
test('Wrong acknowledgement or disk write failure never reports stored/synced',async()=>{const f=fixture();const a=f.store.meter(true).load;await assert.rejects(uploadOne(f.store,a.local_id,'http://example',async()=>({ok:true,json:async()=>({ok:true,id:1,local_id:'wrong',revision:1})})));assert.equal(f.store.status().pending,1);f.store.db.pragma('query_only = ON');assert.throws(()=>f.store.meter(false));assert(!f.store.read(a.local_id).ended_at);f.store.db.pragma('query_only = OFF');f.close();});

test('RFID authorization time is distinct from actual pump start',()=>{const f=fixture();f.store.inventory(roster);const a=f.store.access(event).load;f.time(30000);f.store.meter(false);f.store.meter(true);f.time(1000);const b=f.store.meter(false).load;assert.equal(Date.parse(b.pump_started_at)-Date.parse(a.started_at),30000);assert.equal(Date.parse(b.ended_at)-Date.parse(b.pump_started_at),1000);f.close();});
test('An existing legacy load keeps its meter method through upgrade',()=>{const f=fixture();const a=f.store.meter(true).load;a.meter_method='time_estimate';delete a.pump_started_at;f.store.save(a);f.time(1000);const b=f.store.meter(false).load;assert.equal(b.liters,10);assert.equal(f.store.snapshot(b.local_id).body.flow_l_min,600);f.close();});
